name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "931320c36b611a74d0416268c6b6a3116f89deff442b305225ded482b8256f35"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
