name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fcd206f220eee6ca739154c7a4196357ebcb9522c09bacdb29ef309bf055fa0"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
