name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "922d127a4f5717518deb272f06f582c6fd7367427be4f00713731b13b362c453"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.26"
