name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bfb1dabf1bb767922dcde741b0f1037cf5101c1a11dd887b98f61dedb853ac1"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.68"

[options]
acceptable-game-versions = ["1.19.2"]
