name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91c3f8efac65fdad35b12051bf2438f4f6f4fe185e83f863a1ffca649d0337ee"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.58"
