name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "603e7ff5fc2f2124ce977cb93cfa374a90ba1d4775ae921f87e4e5c7b3fd48d6"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.68"
