name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dad46cb4211ec2fa0641dcb043b396811eae69a27265f6466d00e3c6d40b6d48"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.29"
