name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e8e84725bdf374d3712ae39cbb7d3fa888c2d7f4e71e16550858e279f691c2e"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.68"
