name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d18540138345c37ccca46bd653309077247a71384d59dec88733ebb556dee23c"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.29"
