name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef63f0042df360acd5961b184f27609b44e4163364a000bce64aa1eb5fcbdea8"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.75"
