name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "069de33553ae6384cce4604e4172e83d02de8688b854d88e2b951b7396037425"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.26"
