name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24f727d238a674b5dd75f41339d3cc1ecc41c29aed7a12d233f8b067f2273625"

[versions]
minecraft = "1.18.2"
quilt = "0.18.4-pre.1"
