name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07dc7b3319557c555ab5a6dda5e915d0c0bee7475af69675a5a41fce28c35b8a"

[versions]
minecraft = "1.18.2"
quilt = "0.18.2"
