name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "609a5f732b741c9bb8f7f4fb7d031df0812680bccc9fe489ca2b866080fb3892"

[versions]
minecraft = "1.18.2"
quilt = "0.18.4-pre.1"
