name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ba3254b8d0dcbdadd50710f3a83b8a902bd426c38db5387ef2c2c1c31edb51b"

[versions]
minecraft = "1.18.2"
quilt = "0.18.1-beta.26"
