name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0b66b69bb38f328bdf2afcdb56f9e05272a17b91fabe24624021f8b49259906"

[versions]
minecraft = "1.19.4-pre3"
quilt = "0.18.2"
