name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d343c221a3a875596d0f47e960c7e3924ad52f755f6d7afc20d9b9d7b92363c"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.1"
