name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac91eeac2b69f522036dd1f3b149cf8374e9fd3a4de915064d22d8f78cad9f13"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.26"
