name = "Quilt Optimized"
author = "TheBossMagnus"
version = "0.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd4ee9a41425202b7444ca044373b799fdc5b16d4bc88d2945579cd9c0821356"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.58"
